@echo off
REM Auto-generated by scripts/write_run_bat.py - do not edit by hand.
REM Launch APK Wooper using the .apkwooper Python 3.12 virtualenv.

setlocal ENABLEDELAYEDEXPANSION
set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
pushd "%ROOT%" >nul

set "VENV_PY=%ROOT%\.apkwooper\Scripts\python.exe"
if not exist "%VENV_PY%" (
    echo [run.bat] Virtual environment not found at %VENV_PY%
    echo [run.bat] Run build.bat first to bootstrap the .apkwooper venv.
    popd >nul
    exit /b 1
)

if not exist "%ROOT%\.env" (
    echo [run.bat] WARNING: .env not found in %ROOT%
    echo [run.bat] Falling back to defaults; some features may fail.
    echo [run.bat] Run build.bat to generate .env with secure defaults.
)

echo [run.bat] Starting APK Wooper from %ROOT%
echo [run.bat]   python: %VENV_PY%
echo [run.bat]   MobSF auto-start respects ENABLE_MOBSF in .env.

"%VENV_PY%" -m apk_web
set "RC=%ERRORLEVEL%"

popd >nul
exit /b %RC%
