"""Generate the project's ``run.bat`` Windows launcher.

The generated batch file:

* Validates that the ``.apkwooper`` Python 3.12 venv exists.
* Loads ``.env`` so MobSF / Flask configuration is available.
* Runs ``python -m apk_web``. MobSF is auto-started from inside the
  dashboard process when ``ENABLE_MOBSF=true`` (see
  ``apk_web/app.py::_maybe_autostart_mobsf``), so its lifecycle is tied
  to the dashboard and the atexit hook in ``github_installer.py`` kills
  it when the dashboard exits.

We re-emit the file each build so future tweaks land automatically.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TARGET = REPO_ROOT / "run.bat"

RUN_BAT = r"""@echo off
REM Auto-generated by scripts/write_run_bat.py - do not edit by hand.
REM Launch APK Wooper using the .apkwooper Python 3.12 virtualenv.

setlocal ENABLEDELAYEDEXPANSION
set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
pushd "%ROOT%" >nul

set "VENV_PY=%ROOT%\.apkwooper\Scripts\python.exe"
if not exist "%VENV_PY%" (
    echo [run.bat] Virtual environment not found at %VENV_PY%
    echo [run.bat] Run build.bat first to bootstrap the .apkwooper venv.
    popd >nul
    exit /b 1
)

if not exist "%ROOT%\.env" (
    echo [run.bat] WARNING: .env not found in %ROOT%
    echo [run.bat] Falling back to defaults; some features may fail.
    echo [run.bat] Run build.bat to generate .env with secure defaults.
)

echo [run.bat] Starting APK Wooper from %ROOT%
echo [run.bat]   python: %VENV_PY%
echo [run.bat]   MobSF auto-start respects ENABLE_MOBSF in .env.

"%VENV_PY%" -m apk_web
set "RC=%ERRORLEVEL%"

popd >nul
exit /b %RC%
"""


def main() -> int:
    TARGET.write_text(RUN_BAT, encoding="utf-8")
    print(f"[run-bat] wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
