"""Generate the project's platform-appropriate launcher (``run.bat`` on
Windows, ``run.sh`` on Linux / macOS).

The generated script:

* Validates that the ``.apkwooper`` Python 3.12 venv exists.
* Loads ``.env`` so MobSF / Flask configuration is available.
* Runs ``python -m apk_web``. MobSF is auto-started from inside the
  dashboard process when ``ENABLE_MOBSF=true`` (see
  ``apk_web/app.py::_maybe_autostart_mobsf``), so its lifecycle is tied
  to the dashboard and the atexit hook in ``github_installer.py`` kills
  it when the dashboard exits.

We re-emit the file each build so future tweaks land automatically.
"""

from __future__ import annotations

import platform
import stat
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Windows – run.bat
# ---------------------------------------------------------------------------

RUN_BAT = r"""@echo off
REM Auto-generated by scripts/write_run_script.py - do not edit by hand.
REM Launch APK Wooper using the .apkwooper Python 3.12 virtualenv.

setlocal ENABLEDELAYEDEXPANSION
set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
pushd "%ROOT%" >nul

set "VENV_PY=%ROOT%\.apkwooper\Scripts\python.exe"
if not exist "%VENV_PY%" (
    echo [run.bat] Virtual environment not found at %VENV_PY%
    echo [run.bat] Run build.bat first to bootstrap the .apkwooper venv.
    popd >nul
    exit /b 1
)

if not exist "%ROOT%\.env" (
    echo [run.bat] WARNING: .env not found in %ROOT%
    echo [run.bat] Falling back to defaults; some features may fail.
    echo [run.bat] Run build.bat to generate .env with secure defaults.
)

echo [run.bat] Starting APK Wooper from %ROOT%
echo [run.bat]   python: %VENV_PY%
echo [run.bat]   MobSF auto-start respects ENABLE_MOBSF in .env.

"%VENV_PY%" -m apk_web
set "RC=%ERRORLEVEL%"

popd >nul
exit /b %RC%
"""

# ---------------------------------------------------------------------------
# Linux / macOS – run.sh
# ---------------------------------------------------------------------------

RUN_SH = """\
#!/usr/bin/env bash
# Auto-generated by scripts/write_run_script.py - do not edit by hand.
# Launch APK Wooper using the .apkwooper Python 3.12 virtualenv.

set -euo pipefail

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
cd "$ROOT"

VENV_PY="$ROOT/.apkwooper/bin/python"

if [ ! -x "$VENV_PY" ]; then
    echo "[run.sh] Virtual environment not found at $VENV_PY"
    echo "[run.sh] Run ./build.sh first to bootstrap the .apkwooper venv."
    exit 1
fi

if [ ! -f "$ROOT/.env" ]; then
    echo "[run.sh] WARNING: .env not found in $ROOT"
    echo "[run.sh] Falling back to defaults; some features may fail."
    echo "[run.sh] Run ./build.sh to generate .env with secure defaults."
fi

echo "[run.sh] Starting APK Wooper from $ROOT"
echo "[run.sh]   python: $VENV_PY"
echo "[run.sh]   MobSF auto-start respects ENABLE_MOBSF in .env."

"$VENV_PY" -m apk_web
"""


def _write_windows() -> Path:
    target = REPO_ROOT / "run.bat"
    target.write_text(RUN_BAT, encoding="utf-8")
    return target


def _write_unix() -> Path:
    target = REPO_ROOT / "run.sh"
    target.write_text(RUN_SH, encoding="utf-8")
    # chmod +x
    target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return target


def main() -> int:
    system = platform.system()
    if system == "Windows":
        target = _write_windows()
    else:
        # Darwin (macOS) and Linux both get a POSIX shell script.
        target = _write_unix()

    print(f"[write-run-script] wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())